/* Item 1 */
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Caesar Salad & Grilled Chicken',25.00,'Salada de alface americana com molho à base de creme de leite, parmesão e alho, tiras de frango grelhado, croûtons e queijo parmesão.','http://www.restauranteamerica.com.br/arquivos/cardapio/salada/caesar-salad-grilled-chicken.jpg',1,1);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Carpaccio America',20.00,'Carpaccio, alface americana e rúcula temperadas com molho de alcaparras, azeitonas pretas, croûtons e queijo parmesão.','http://www.restauranteamerica.com.br/arquivos/cardapio/salada/carpaccio-america.jpg',1,1);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Salada Flórida',28.00,'Salada de alface americana e frizzé, tomate cereja, abacaxi, mozzarella de búfala, tiras de frango grelhado, croûtons e molho vinagrete, salpicada com manjericão.','http://www.restauranteamerica.com.br/arquivos/cardapio/salada/salada-florida.jpg',1,1);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Salada Italiana',15.00,'Salada de alface americana, tomate seco, mozzarella de búfala, gomos de laranja, azeitonas pretas, salpicada com manjericão, croûtons e molho vinagrete.','http://www.restauranteamerica.com.br/arquivos/cardapio/salada/salada-italiana.jpg',1,1);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Salada Oriental',18.00,'Salada de alface americana, cenoura, pepino, manga, com molho honey mustard e tiras de frango grelhado, salpicada com gergelim torrado.','http://www.restauranteamerica.com.br/arquivos/cardapio/salada/salada-oriental.jpg',1,1);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Steak Salad',18.00,'Salada de alface americana, rúcula, radicchio, tomate cereja e palmito com molho vinagrete, tiras de filet mignon ao molho de mostarda ancienne e croûtons.','http://www.restauranteamerica.com.br/arquivos/cardapio/salada/steak-salad.jpg',1,1);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Super Yuppie',20.00,'Salada de agrião, tomate cereja, mozzarella de búfala e cogumelos frescos sobre uma base de folhas de alface americana, com molho de azeite, limão e alcaparras.','http://www.restauranteamerica.com.br/arquivos/cardapio/salada/super-yuppie.jpg',1,1);

/* Item 3 */
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Caesar Pasta',85.00,'Fettuccine com molho Caesar à base de creme de leite, parmesão e alho, acompanhado de tiras de frango grelhado e farofa crocante de pão, parmesão e manjericão.','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/caesar-pasta.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Fettuccine',85.50,'Fettuccine (massa branca ou verde preparada no próprio America com sêmola de grano duro) com molho a sua escolha','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/fettuccine.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Mexican italian',85.50,'Fettuccine servido com hamburger de 200 gramas, coberto com TexMex levemente apimentado e queijo provolone derretido.','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/mexican-italian.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Paillard de Frango & Pasta',87.00,'Fettuccine servido com paillard de frango de 150 gramas','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/paillard-de-frango-pasta.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Paillard de Mignon & Pasta',86.00,'Fettuccine servido com paillard de filet mignon de 150 gramas','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/paillard-de-mignon-pasta.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Penne',84.00,'Penne com molho a sua escolha','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/penne.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Penne Caprese',88.00,'Penne com tomates cereja assados com ervas frescas, mozzarella de búfala, manjericão e queijo pecorino.','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/penne-caprese.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Polpettone',83.00,'Servido com fettuccine ou penne ao molho de tomates e manjericão.','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/polpettone.jpg',1,3);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Sorrentini de Búfala',90.00,'Massa verde fresca recheada com mozzarella de búfala servida com molho de tomates e manjericão.','http://www.restauranteamerica.com.br/arquivos/cardapio/pasta/sorrentini-de-bufala.jpg',1,3);

/* Item 5 */
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Beirute América',60.00,'Queijo prato derretido, alface, tomate, maionese e relish de pepino, no pão sírio, a sua escolha','http://www.restauranteamerica.com.br/arquivos/cardapio/sanduiche/beirute-america.jpg',1,5);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Churrasquinho na Baguete',65.00,'Queijo prato derretido, alface, tomate, maionese e relish de pepino, no pão sírio, a sua escolha','http://www.restauranteamerica.com.br/arquivos/cardapio/sanduiche/churrasquinho-na-baguete.jpg',1,5);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Times square Dog',30.00,'Delicioso hot dog com salsicha especial grelhada, coberta com delicioso molho cremoso de queijos, acompanhado de potinho de mostarda com ervas, no pão baguete. Servido com onion rings ou batatas fritas.','http://www.restauranteamerica.com.br/arquivos/cardapio/sanduiche/times-square-dog.jpg',1,5);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Veggie Sandwich',30.00,'Sanduíche de berinjela grelhada, abobrinha grelhada, mozzarella de búfala, tomate seco e rúcula com molho mostarda, no pão ciabatta.','http://www.restauranteamerica.com.br/arquivos/cardapio/sanduiche/veggie-sandwich.jpg',1,5);

/* Item 7 */
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Special Carne',35.00,'Fraldinha de 150 gramas ou baby picanha de 150 gramas com queijo provolone grelhado acompanhada de batatas fritas e arroz.','http://www.restauranteamerica.com.br/arquivos/cardapio/special/special-carne.jpg',1,7);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Special Frango',40.00,'Filet de peito de frango grelhado de 120 gramas acompanhado de creme de milho e arroz.','http://www.restauranteamerica.com.br/arquivos/cardapio/special/special-frango.jpg',1,7);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Special Peixe',45.00,'Filet de saint peter de 180 gramas ou filet de truta de 180 gramas com molho dill, acompanhado de arroz primavera e batatas grelhadas.','http://www.restauranteamerica.com.br/arquivos/cardapio/special/special-peixe.jpg',1,7);

/* Item 9 */
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('2 Mini Cheesburgers + Fritas + Bebida a escolha',20.00,'Refrigerante, Suco, MilkShake','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/2-mini-cheeseburgers-com-fritas-com-bebida-a-escolha.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Cheesburger Kids',30.00,'Cheeseburger 150 gramas.','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/cheeseburger-kids.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Fettuccine ou  Penne',40.00,'Com molho a escolha','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/fettuccine-ou-penne.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Fettucine ou Penne + Bifinho de Filet Mignon',35.00,'Molho de Manteiga, Tomates ou Queijos.','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/fettuccine-ou-penne-com-bifinho-de-filet-mignon.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Fettucine ou Penne + Filet de Frango',35.00,'Molho de Manteiga, Tomates ou Queijos.','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/fettuccine-ou-penne-com-bifinho-de-filet-mignon.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Hamburger Kids',37.00,'Hamburger 150 gramas.','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/fettuccine-ou-penne-com-bifinho-de-filet-mignon.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Hot Dog + Fritas + Bebida a escolha',27.00,'Refrigerante, Suco, MilkShake','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/hot-dog-com-fritas-com-bebida-a-escolha.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Nuggets de Frango + Fritas + Bebida a escolha',25.00,'Refrigerante, Suco, MilkShake','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/nuggets-de-frango-com-fritas-com-bebida-a-escolha.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Taça Brigadeiro',30.00,'Uma bola de sorvete de creme com brigadeiro de colher e canudinho de chocolate.','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/taca-brigadeiro.jpg',1,9);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Taça Kids',45.00,'Uma bola de sorvete com calda de chocolate ou morango.','http://www.restauranteamerica.com.br/arquivos/cardapio/crianca/taca-kids.jpg',1,9);

/* Item 11 */
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Cerveja Budweiser',9.00,'Cerveja Budweiser (300 ml)','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/cerveja-budweiser.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Cerveja Erdinger',9.00,'500 ml','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/cerveja-erdinger.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Cerveja Stella Artois',9.00,'Cerveja Stella Artois (275 ml)','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/cerveja-stella-artois.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Milk shake',9.00,'Chocolate, creme, morango ou flocos.','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/milk-shake-300-ml.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Suco',5.00,'Suco natural','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/suco.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Refrigerante',4.50,'Lata','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/refrigerante.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Milk Shake Farofino',8.50,'Milk Shake de chocolate com farofa crocante, cobertura de chocolate e creme chantilly.','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/milk-shake-farofino-300-ml.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Milk Shake 500 ml',13.00,'Chocolate, creme, morango ou flocos.','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/milk-shake-500-ml.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Lipton Ice Tea',6.00,'Lata','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/lipton-ice-tea.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Lipton Chá Verde',6.00,'Lata','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/lipton-cha-verde.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Água de Coco',3.00,'','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/agua-de-coco.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Água mineral',2.50,'300ml com ou sem gás','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/agua-mineral.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Tônica Schweppes',5.50,'Lata','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/tonica-schweppes.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('H2OH!',5.50,'500 ml','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/h2oh.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Cerveja bohemia',8.50,'355ml','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/cerveja-bohemia.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Cerveja Cerpa',8.50,'350ml','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/cerveja-cerpa.jpg',1,11);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Cerveja xingu',8.50,'355 ml','http://www.restauranteamerica.com.br/arquivos/cardapio/bebida/cerveja-xingu.jpg',1,11);


/* Item 13 */
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Capelletti in Brodo',19.90,'Cappelletti in brodo: Cappelletti com caldo de carne. Acompanha croûtons temperados e queijo parmesão ralado.','http://www.restauranteamerica.com.br/arquivos/cardapio/sopa/cappelletti-in-brodo.jpg',1,13);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Creme de Mandioquinha',19.90,'Creme de Mandioquinha com funghi secchi: Creme de Mandioquinha com funghi secchi e acompanha croûtons temperados.','http://www.restauranteamerica.com.br/arquivos/cardapio/sopa/creme-de-mandioquinha.jpg',1,13);
insert into item (name, price, description, urlImage, id_restaurant,id_type) values ('Creme de Palmito',19.90,'Creme de Palmito Pupunha: Creme de Palmito Pupunha com Lemon Pepper e acompanha croûtons temperados.','http://www.restauranteamerica.com.br/arquivos/cardapio/sopa/creme-de-palmito.jpg',1,13);
